accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup_view, name="signup"),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug>/',views.article_detail, name='detail'),
    path('article/<int:pk>/comment/', views.add_comment_to_article, name='add_comment_to_article'),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', article_views.article_list, name='home'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('allauth.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User,default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

class Comment(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE, related_name='comments')
    user = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

articles/forms.py
from django import forms
from . import models
from .models import Article, Comment


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb',]

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('user', 'text',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('articles:list')

articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms
from .forms import CommentForm

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', { 'articles': articles })

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', { 'article': article })

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

def add_comment_to_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            return redirect("articles:detail", slug=article.slug)
    else:
        form = CommentForm()
    return render(request, 'articles/add_comment_to_article.html', {'form': form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = 'home.html'


def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')


def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% load socialaccount %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Signup">
        <a style="background-color: #3b5998; padding: 7px; border-radius: 4px;"  href="{% provider_login_url 'facebook' %}">Facebook Sign Up
        </a>
    </form>
{% endblock %}

articles/templates/articles/add_comment_to_article.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="article-form">{% csrf_token %}
        {{ form|crispy }}
        <button style="background-color: white; color:black; padding: 7px; border-radius: 4px" type="submit" class="save btn btn-default">Comment</button>
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>

<br>
<br>

<a style="background-color: white; color:black; padding: 10px; border-radius: 4px; margin:5px" class="btn btn-default" href="{% url 'articles:add_comment_to_article' pk=article.pk %}">Add comment</a>

{% for comment in article.comments.all %}
    <div style="margin:20px;"  class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.user }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
        <hr>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %}
        <div class="categories">
            <ul style="list-style: none; margin-left=100px">
                <li style="display: inline-block; padding-left:20px; margin-left=100px;"><a href="#">Science</a></li>
                <li style="display: inline-block; padding-left:20px; margin-left=100px"><a href="#">Technology</a></li>
                <li style="display: inline-block; padding-left:20px; margin-left=100px"><a href="#">Arts</a></li>
                <li style="display: inline-block; padding-left:20px; margin-left=100px"><a href="#">Philosophy</a></li>
                <li style="display: inline-block; padding-left:20px; margin-left=100px"><a href="#">Entertainment</a></li>
                <li style="display: inline-block; padding-left:20px; margin-left=100px"><a href="#">Travel</a></li>
            </ul>
        </div>

        <h1>Articles</h1>
        <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                <p>{{ article.snippet }}</p>
                <p>{{ article.date }}</p>
                <p class="author">added by {{article.author.username}}</p>
            </div>
        {% endfor %}
        </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>about</title>
  </head>
  <body>
    <h1>about us</h1>
    <p>this is about page</p>
  </body>
</html>

templates/base_layout.html
{% load static from staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1 class="logo"><a href="{% url 'home' %}"><img style="width:180px;height:40px;" src="{% static 'logo3.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home page</title>
  </head>
  <body>
    <h1>This is Home page</h1>
    <p>welcome to homepage of django nautics</p>
  </body>
</html>